=== Basketigge/InPUT/InPUT_HelloWorld_Watchmaker/DesignSpace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://TheInPUT.org/DesignSpace"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:i="http://TheInPUT.org/DesignSpace">
	<!-- ******************************************************* -->
	<!-- ROOT -->
	<!-- ******************************************************* -->

	<xsd:element name="DesignSpace" type="i:designSpaceType" />


	<!-- ******************************************************* -->
	<!-- END -->
	<!-- ******************************************************* -->



	<!-- ******************************************************* -->
	<!-- DESIGN SPACE TYPE designSpaceType -->
	<!-- ******************************************************* -->
	<xsd:complexType name="designSpaceType">
		<xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="SChoiceType" type="i:structChoiceType" />
			</xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="mapping" type="xsd:string" />
	</xsd:complexType>

	<!-- ******************************************************* -->
	<!-- END -->
	<!-- ******************************************************* -->


	<!-- ******************************************************* -->
	<!-- STRUCTURED PARAM TYPE structParamType -->
	<!-- ******************************************************* -->
	<xsd:complexType name="complexParamType">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SChoice" type="i:structChoiceType" />
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attribute name="fixed" type="xsd:string" />
	</xsd:complexType>

	<!-- ******************************************************* -->
	<!-- END -->
	<!-- ******************************************************* -->



	<!-- ******************************************************* -->
	<!-- STRUCTURED CHOICE TYPE structChoiceType -->
	<!-- ******************************************************* -->
	<xsd:complexType name="structChoiceType">
		<xsd:sequence>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
				<xsd:choice>
					<xsd:element name="SParam" type="i:complexParamType" />
					<xsd:element name="NParam" type="i:numericType" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string" />
		<xsd:attributeGroup ref="i:idAttributes" />
	</xsd:complexType>

	<!-- ******************************************************* -->
	<!-- END -->
	<!-- ******************************************************* -->



	<!-- ******************************************************* -->
	<!-- NUMERIC STRUCTURED TYPE numericType -->
	<!-- ******************************************************* -->

	<xsd:complexType name="numericType">
		<xsd:attribute name="inclMin" type="xsd:anySimpleType" />
		<xsd:attribute name="exclMin" type="xsd:anySimpleType" />
		<xsd:attribute name="inclMax" type="xsd:anySimpleType" />
		<xsd:attribute name="exclMax" type="xsd:anySimpleType" />
		<xsd:attribute name="fixed" type="xsd:string" />
		<xsd:attributeGroup ref="i:idAttributes" />
		<xsd:attribute name="type" type="xsd:anySimpleType" use="required" />
	</xsd:complexType>

	<!-- ******************************************************* -->
	<!-- END -->
	<!-- ******************************************************* -->



	<!-- ******************************************************* -->
	<!-- IDENTIFIER ATTRIBUTE GROUP idAttributes -->
	<!-- ******************************************************* -->

	<xsd:attributeGroup name="idAttributes">
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" />
	</xsd:attributeGroup>

	<!-- ******************************************************* -->
	<!-- END -->
	<!-- ******************************************************* -->

</xsd:schema>

=== Basketigge/InPUT/Java/Source/InPUT4j_Test/realPSO.xml
<?xml version="1.0" encoding="UTF-8"?>
<i:DesignSpace id="realPSO"
	xmlns:i="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://TheInPUT.org/DesignSpace http://TheInPUT.org/DesignSpace.xsd ">
	<i:NParam id="Seed" type="decimal" />
	<i:NParam id="PopSize" type="integer" inclMin="2" inclMax="50"/>
	<i:NParam id="InitPosMin" type="decimal" inclMin="-4" inclMax="-1"/>
	<i:NParam id="InitPosMax" type="decimal" inclMin="1" inclMax="4"/>
	<i:NParam id="InitVelMin" type="decimal" inclMin="-3" inclMax="-0.5"/>
	<i:NParam id="InitVelMax" type="decimal" inclMin="0.5" inclMax="3"/>
	<i:NParam id="VelMin" type="decimal" inclMin="-4" inclMax="-0.5"/>
	<i:NParam id="VelMax" type="decimal" inclMin="0.5" inclMax="4"/>
	<i:SParam id="VelocityType">
		<i:SParam id="Topology">
			<i:NParam id="Neighborhood" type="integer" inclMin="2" inclMax="10"/>
			<i:SChoice id="Ring" />
			<i:SChoice id="Linear" />
		</i:SParam>
		<i:NParam id="Inertia" type="decimal" inclMin="0" inclMax="5" />
		<i:NParam id="LFactor1" type="decimal" inclMin="0.1" inclMax="3" />
		<i:NParam id="LFactor2" type="decimal" inclMin="0.1" inclMax="5" />
		<i:SChoice id="Standard" />
		<i:SChoice id="Constricted" />
		<i:SChoice id="FixedInertiaWeight" />
		<i:SChoice id="VariableInertiaWeight" />
		<i:SChoice id="Extended">
			<i:NParam id="LFactor3" type="decimal" inclMin="0" inclMax="5" />
		</i:SChoice>
	</i:SParam>
	<i:SParam id="StopCriterion">
		<i:SChoice id="Time">
			<i:NParam id="Ms" type="integer" inclMin="1" />
		</i:SChoice>
		<i:SChoice id="Generations">
			<i:NParam id="Amount" type="integer" inclMin="2" inclMax="100" />
		</i:SChoice>
		<i:SChoice id="SteadyFit">
			<i:NParam id="MinGen" type="integer" inclMin="10" inclMax="50" />
			<i:NParam id="Interval" type="integer" inclMin="1" inclMax="20" />
		</i:SChoice>
	</i:SParam>
</i:DesignSpace>

=== Basketigge/InPUT/Java/Source/InPUT4j_Test/geneticAlgorithm.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:DesignSpace id="ga" mapping="geneticAlgorithmMapping.xml"
	xmlns:in="http://TheInPUT.org/DesignSpace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="www.TheInPUT.org/DesignSpace.xsd www.TheInPUT.org/DesignSpace.xsd">
	<in:SChoiceType id="SomeNoneSenseType">
		<in:NParam type="integer" id="Points" inclMin="1" />
	</in:SChoiceType>
	<in:NParam id="popSize" type="decimal" inclMin="-12.23434"
		inclMax="-12.23433" />
	<in:NParam id="featureX" type="boolean" fixed="false" />
	<in:NParam id="mutationRate" type="double[][]" exclMin="0.0001"
		inclMax="0.4" />
	<in:SParam id="representation">
		<in:NParam type="double" id="color" />
		<in:SChoice id="bit" />
		<in:SChoice id="real" />
	</in:SParam>
	<in:SParam id="mutation" type="[]">
		<in:NParam id="wrapped" type="double" />
		<in:NParam id="length" type="decimal" inclMin="popSize-20"
			inclMax="popSize+20" />
		<in:NParam id="positions" type="integer" inclMin="1"
			inclMax="10" />
		<in:SChoice id="flip" />
		<in:SChoice id="slide" />
	</in:SParam>
	<in:SParam id="selection">
		<in:SChoice id="tournament">
			<in:NParam id="size" type="integer" inclMin="5" inclMax="20" />
			<in:NParam id="winner" type="integer" exclMin="0"
				inclMax="selection.tournament.size-1" />
			<in:SParam id="someDecision">
				<in:SChoice id="value1" />
				<in:SChoice id="value2" />
			</in:SParam>
		</in:SChoice>
		<in:SChoice id="rank" />
		<in:SChoice id="roulette" />
	</in:SParam>
	<in:SParam id="localSearch">
		<in:SParam id="helper">
			<in:SChoice id="simpleHelper" />
			<in:SChoice id="advancedHelper" />
		</in:SParam>
		<in:SChoice id="2-opt" />
		<in:SChoice id="3-opt" />
	</in:SParam>
	<in:NParam id="dependee" type="decimal" inclMin="mutation.length-1"
		inclMax="mutation.length+1" />
	<in:SParam id="theChoice">
		<in:SChoice id="first" />
		<in:SChoice id="second" />
		<in:SChoice id="third" />
	</in:SParam>
	<in:SParam id="network">
		<in:NParam type="integer" id="something" />
		<in:SParam id="instance" />
	</in:SParam>
</in:DesignSpace>
