=== Basketigge/InPUT/InPUT_XML/GiveInPUT.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://apachepersonal.miun.se/feldob/GiveInPUT" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:m="http://apachepersonal.miun.se/feldob/InPUT" xmlns:i="http://apachepersonal.miun.se/feldob/GiveInPUT">
<xsd:import namespace="http://apachepersonal.miun.se/feldob/InPUT"
schemaLocation="InPUT.xsd"/>

	<!-- ******************************************************* -->
	<!-- 						ROOT							 -->
	<!-- ******************************************************* -->
	
<xsd:element name="GiveInPUT" type="i:structType"/>

	<!-- ******************************************************* -->
	<!-- 						END								 -->
	<!-- ******************************************************* -->	



	<!-- ******************************************************* -->
	<!-- ALGORITHM STRUCTURED TYPE		structType				 -->
	<!-- ******************************************************* -->
	
	   <xsd:complexType name="structType">
    	<xsd:sequence maxOccurs="unbounded" minOccurs="0">
 	    <xsd:choice>
    		<xsd:element name="StructValue" type="i:structType"/>
    		<xsd:element name="NumericValue" type="i:numericType"/>
    	</xsd:choice>
    	</xsd:sequence>
    	<xsd:attributeGroup ref="m:idAttributes"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>	
		<xsd:attribute name="design" type="xsd:boolean" default="false"/>
    </xsd:complexType>

	<!-- ******************************************************* -->
	<!-- 						END								 -->
	<!-- ******************************************************* -->	



	<!-- ******************************************************* -->
	<!-- ALGORITHM NUMERIC TYPE		algorithm					 -->
	<!-- ******************************************************* -->
  
    <xsd:complexType name="numericType">
			<xsd:attributeGroup ref="m:idAttributes"/>
			<xsd:attribute name="value" type="xsd:anySimpleType" use="required"/>
  </xsd:complexType>

  	<!-- ******************************************************* -->
	<!-- 						END								 -->
	<!-- ******************************************************* -->	

</xsd:schema>

=== Basketigge/InPUT/InPUT_XML/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:GiveInPUT type="ga" xmlns:in="http://apachepersonal.miun.se/feldob/GiveInPUT" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://apachepersonal.miun.se/feldob/GiveInPUT GiveInPUT.xsd ">
    <in:NumericValue id="popSize" value="10"/>
    <in:NumericValue id="mutationRate" value="0.1"/>
    <in:StructValue id="selection" type="se.miun.itm.feldob.ga.Tournament">
    	<in:NumericValue id="size" value="20"/>
    	<in:NumericValue id="winner" value="3"/>	  
    	<in:StructValue id="c" type="a"/>
  	</in:StructValue>
  	<in:StructValue id="selection" type="se.miun.itm.feldob.ga.Tournament">
    	<in:NumericValue id="size" value="10"/>
    	<in:NumericValue id="winner" value="1"/>	  
    	<in:StructValue id="c" type="a"/>
  	</in:StructValue>
  	<in:StructValue id="a" type="a"/>
  	<in:StructValue id="b" type="a"/>
</in:GiveInPUT>
